version: '3.8'

networks:
  userhub-network:
    driver: bridge

services:

  nginx:
    image: nginx:latest
    container_name: userhub-nginx
    ports:
      - "4444:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./auth.stl:/etc/nginx/auth.stl:ro
    restart: unless-stopped
    depends_on:
      - backend
      - frontend

    networks:
      - userhub-network

  postgres:
    image: postgres:16-alpine
    container_name: userhub-postgres
    restart: unless-stopped
    environment: 
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${EXTERNAL_POSTGRES_PORT}:5432"
    networks:
      - userhub-network

  backend:
    build: ./backend
    container_name: userhub-backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5555:5555"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app/
    networks:
      - userhub-network

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=http://localhost:5555
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - userhub-network

  migrate:
    build: ./backend
    command: alembic upgrade head
    env_file:
      - .env
    depends_on:
      - postgres
    profiles: ["tools"]


    
volumes:
  postgres_data:

